-- Human-readable transaction number for owner/cashier lookup.
-- UUID remains the technical primary key and sync idempotency key.

alter table public.transactions
  add column if not exists transaction_number text;

comment on column public.transactions.transaction_number is
  'Human-readable transaction number generated by the client, format YYMMDDHHMI-XXX. Nullable for legacy rows.';

create unique index if not exists transactions_branch_transaction_number_uq
  on public.transactions (branch_id, transaction_number)
  where transaction_number is not null;
